name: ie-bank-infra

on:
  workflow_dispatch: #Allows you to manually trigger the workflow from the GitHub Actions tab.

env:
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  SUBSCRIPTION_ID: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: zalsaheb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
      - uses: actions/checkout@main

      # Lint Bicep code
      - name: Run Bicep linter
        run: az bicep build --file ./infra/main.bicep

      - name: Upload Bicep build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bicep-build
          path: ./infra/main.bicep  # Updated path to infra directory

  deploy-dev:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build

    steps:

      # Checkout code
    - uses: actions/checkout@main

    - name: Download Bicep build artifact
      uses: actions/download-artifact@v4
      with:
          name: bicep-build

      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy to dev
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./infra/main.bicep
        parameters: ./infra/parameters/dev.parameters.json
        deploymentName: ${{ env.USER_ALIAS }}-dev
